version: '3'
services:
  db:
    image: postgres
  web:
    image: nam20485/dockersite:initial
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
        - webnet
networks:
    webnet:
